### ISSUE TITLE
How can I upload the failed files again?

### ISSUE THREAD

**Issue by kof0012** [WardPearce/aiob2#12]
When I use asyncio to upload dozens of files concurrently, the following errors often occur. I use Ubuntu system. How can I upload the failed files again?
`uploadtasks = [bucket.upload_file(UploadSettings(channelid + "/" + singlepath.name),singlepath) for singlepath in collectpath if singlepath]
 
filemodel, waittingfile = await asyncio.wait(uploadtasks)
 
print("WWWWWWWaiting", waittingfile)
 
if not waittingfile:
     return True`

`Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backblaze/bucket/awaiting/__init__.py", line 213, in upload_file
    data, file = await self.upload(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backblaze/bucket/awaiting/__init__.py", line 240, in upload
    file = FileModel(await self._context._post(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backblaze/http/awaiting.py", line 55, in _post
    return await self.__handle(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/backblaze/http/awaiting.py", line 25, in __handle
    resp = await request(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1789, in post
    return await self.request(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1483, in request
    response = await self.send(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1571, in send
    response = await self._send_handling_auth(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1599, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1636, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1673, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 270, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 79, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
Task exception was never retrieved
future: <Task finished name='Task-449' coro=<AwaitingBucket.upload_file() done, defined at /home/ubuntu/.local/lib/python3.10/site-packages/backblaze/bucket/awaiting/__init__.py:177> exception=ConnectError('')>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 62, in map_httpcore_exceptions
    yield
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 276, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 147, in open_tcp_stream
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError`

**Comment by WardPearce** [comment]
Not tested, but you could implement something like this. Connection error most likely caused by requests being sent too quickly

```py
import asyncio
import backblaze

from httpx import ConnectError


bucket = backblaze.Awaiting(
    "..", "..."
)


async def retry_if_fail(upload_settings, path) -> None:
    error = True

    while error:
        try:
            await bucket.upload_file(upload_settings, path)
        except ConnectError:
            await asyncio.sleep(3.0)
        else:
            error = False



async def main() -> None:
    await asyncio.gather(*[
        retry_if_fail(..., singlepath)
        for singlepath in collectpath if singlepath
    ])
```

**Comment by kof0012** [comment]
Thank you very much for your reply. That's a clever way
